version: '2.1'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab$DOMAIN'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab$DOMAIN'
    networks:
      dire_net:
        ipv4_address: $GIT_HOST
    volumes:
      - 'gitlab-config:/etc/gitlab'
      - 'gitlab-logs:/var/log/gitlab'
      - 'gitlab-data:/var/opt/gitlab'

#  gitlab_runner:
#    image: 'gitlab/gitlab-runner:latest'
#    restart: always
#    volumes:
#      - '/var/run/docker.sock:/var/run/docker.sock'
#      - 'gitlab-runner-config:/etc/gitlab-runner'

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  gitlab-runner-config:

networks:
  dire_net:
    external:
      name: $DIRE_NET
#    driver: macvlan
#    ipam:
#      driver: default
#      config:
#      - subnet: $DIRE_SUBNET
#        gateway: $DIRE_GATWAY
#      options:
#        parent: $DIRE_INTERFACE
#       ip-range: $DIRE_IP_RANGE
