version: '3'
services:
  nexus3_init:
    image: "sonatype/nexus3:latest"
    user: root
    volumes:
      - /opt/dire/ssl:/opt/sonatype/nexus/etc/ssl
      - /opt/dire/etc:/etc/dire
      - ./nexus3/init_key.sh:/usr/bin/init_key.sh
    command: bash /usr/bin/init_key.sh
    env_file: env

  nexus3:
    image: "sonatype/nexus3:latest"
    ports:
      - "80:8081"
      - "443:9443"
    volumes:
      - nexus3-data:/nexus-data
      - /opt/dire/ssl:/opt/sonatype/nexus/etc/ssl
      - ./nexus3/nexus-default.properties:/opt/sonatype/nexus/etc/nexus-default.properties:ro
      - ./nexus3/jetty-https.xml:/opt/sonatype/nexus/etc/jetty/jetty-https.xml:ro
    depends_on:
      - nexus3_init
    env_file: env
    restart: always

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.$DOMAIN'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://$HOST_NAME'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '8080:80'
      - '8443:443'
      - '8022:22'
    volumes:
      - 'gitlab-config:/etc/gitlab'
      - 'gitlab-logs:/var/log/gitlab'
      - 'gitlab-data:/var/opt/gitlab'

  gitlab_runner:
    image: 'gitlab/gitlab-runner:latest'
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'gitlab-runner-config:/etc/gitlab-runner'

volumes:
  nexus3-data:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  gitlab-runner-config:
