version: '2.1'
services:
  nexus3_init:
    image: "sonatype/nexus3:latest"
    user: root
    volumes:
      - /opt/dire/ssl:/opt/sonatype/nexus/etc/ssl
      - /opt/dire/etc:/etc/dire
      - ./nexus3/init_key.sh:/usr/bin/init_key.sh
    command: bash /usr/bin/init_key.sh
    env_file: env

  nexus3:
    image: "sonatype/nexus3:latest"
    ports:
      - "80:8081"
      - "443:9443"
    volumes:
      - nexus3-data:/nexus-data
      - /opt/dire/ssl:/opt/sonatype/nexus/etc/ssl
      - ./nexus3/nexus-default.properties:/opt/sonatype/nexus/etc/nexus-default.properties:ro
      - ./nexus3/jetty-https.xml:/opt/sonatype/nexus/etc/jetty/jetty-https.xml:ro
    depends_on:
      - nexus3_init
    env_file: env
    restart: always
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8081']
      interval: 1m30s
      timeout: 10s
      retries: 3

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab$DOMAIN'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab$DOMAIN'
    networks:
      dire_net:
        ipv4_address: $GIT_HOST
    volumes:
      - 'gitlab-config:/etc/gitlab'
      - 'gitlab-logs:/var/log/gitlab'
      - 'gitlab-data:/var/opt/gitlab'

#  gitlab_runner:
#    image: 'gitlab/gitlab-runner:latest'
#    restart: always
#    volumes:
#      - '/var/run/docker.sock:/var/run/docker.sock'
#      - 'gitlab-runner-config:/etc/gitlab-runner'

volumes:
  nexus3-data:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  gitlab-runner-config:

networks:
  dire_net:
    external:
      name: $DIRE_NET
#    driver: macvlan
#    ipam:
#      driver: default
#      config:
#      - subnet: $DIRE_SUBNET
#        gateway: $DIRE_GATWAY
#      options:
#        parent: $DIRE_INTERFACE
#       ip-range: $DIRE_IP_RANGE
